### ISSUE TITLE
多个grpc怎么一次性全部启动?

### ISSUE THREAD

**Issue by Jacktbak** [RonadoLong/fortune-bd#3]

**Comment by RonadoLong** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    不行哦，这个是微服务架构
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                hongronado
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2022年05月18日 10:36
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              [RonadoLong/fortune-bd] 多个grpc怎么一次性全部启动? (Issue #3)
        
      
    
  
  

启动了common-svc里面main.go ,就无法启动 exchange-svc 下面的main.go , 难道不能一次性全部启动所有服务吗？



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by RonadoLong** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    分开启动就好了
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                hongronado
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2022年05月19日 01:42
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              回复：[RonadoLong/fortune-bd] 多个grpc怎么一次性全部启动? (Issue #3)
        
      
    
  
  
    
    不行哦，这个是微服务架构
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                hongronado
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2022年05月18日 10:36
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              [RonadoLong/fortune-bd] 多个grpc怎么一次性全部启动? (Issue #3)
        
      
    
  
  

启动了common-svc里面main.go ,就无法启动 exchange-svc 下面的main.go , 难道不能一次性全部启动所有服务吗？



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
